# Generated by Django 6.0.3 on 2026-03-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('applied_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
